apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jma-discovery
  labels: 
     app: jma-discovery
spec:
  serviceName: "jma-discovery"
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      app: jma-discovery
  template:
    metadata:
      labels:
        app: jma-discovery
    spec:
      imagePullSecrets:
      - name: docker-registry-key
      containers:
      - name: jma-discovery
        image: image-location
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
