apiVersion: v1
kind: Service
metadata:
  name: java-app
  labels:
    app: devops-project
spec:
  selector:
    app: devops-project
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080